services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    restart: unless-stopped

    ports:
      - "8123:8123"
      - "9000:9000"

    environment:
      CLICKHOUSE_DB: transport
      CLICKHOUSE_USER: click
      CLICKHOUSE_PASSWORD: click
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: "1"

    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
  
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - clickhouse
    volumes:
      - metabase_data:/metabase-data
    environment:
      MB_DB_FILE: /metabase-data/metabase.db

volumes:
  clickhouse_data:
  clickhouse_logs:
  metabase_data: